[package]
authors = ["i5hi, mocodesmo"]
description = "Rust-C FFI exposing composite functionality to build bitcoin descriptor wallets."
edition = "2018"
keywords = ["bitcoin", "rust-c-ffi"]
license = "MIT"
name = "stackmate"
version = "0.7.15"
[dependencies]
bip39 = "1.0.1"
hex = "0.4.3"
libtor = "46.6.1+0.4.6.6"
openssl = "0.9.7"
serde = "1.0.126"
serde_derive = "1.0.0"
serde_json = "1.0.64"
sha-1 = "0.9.8"

[dependencies.bdk]
features = ["compiler", "rpc", "electrum"]
version = "0.12.0"

[dependencies.bitcoin]
features = ["rand", "base64"]
version = "0.27.1"

[lib]
crate-type = ["staticlib", "cdylib"]
name = "stackmate"

[profile]
[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
