[package]
name = "stackmate"
version = "0.7.15"
authors = ["i5hi, mocodesmo"]
edition = "2018"
description = "Rust-C FFI exposing composite functionality to build bitcoin descriptor wallets."
keywords = ["bitcoin","rust-c-ffi"]
license = "MIT"

[lib]
name = "stackmate"
crate-type = ["staticlib", "cdylib"]

[dependencies]
hex = "0.4.3"
sha-1 = "0.9.8"
serde = "1.0.126"
serde_json = "1.0.64"
serde_derive = "1.0.0"
bip39 = "1.0.1"
bitcoin ={version = "0.27.1", features = ["rand", "base64"]}
bdk = {version = "0.12.0", features = ["compiler", "rpc", "electrum"]}
libtor = "46.6.1+0.4.6.6"

[target.aarch64-linux-android.dependencies] 
openssl-sys = { version = "*", features = ["vendored"] }

[target.i686-linux-android.dependencies] 
openssl-sys = { version = "*", features = ["vendored"] }

[target.x84_64-linux-android.dependencies] 
openssl-sys = { version = "*", features = ["vendored"] }
